// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_logs.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (
    id,
    actor_user_id,
    action,
    resource_type,
    resource_id,
    ip_address,
    user_agent,
    metadata,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
`

type CreateAuditLogParams struct {
	ID           uuid.UUID  `json:"id"`
	ActorUserID  *uuid.UUID `json:"actor_user_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   *string    `json:"resource_id"`
	IpAddress    string     `json:"ip_address"`
	UserAgent    string     `json:"user_agent"`
	Metadata     []byte     `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}
