// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_tokens.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (
    id,
    user_id,
    token_hash,
    purpose,
    expires_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) RETURNING
    id,
    user_id,
    token_hash,
    purpose,
    expires_at,
    used_at,
    created_at
`

type CreateAuthTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT
    id,
    user_id,
    token_hash,
    purpose,
    expires_at,
    used_at,
    created_at
FROM auth_tokens
WHERE token_hash = $1
`

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markAuthTokenUsed = `-- name: MarkAuthTokenUsed :exec
UPDATE auth_tokens
SET used_at = NOW()
WHERE id = $1
  AND used_at IS NULL
`

func (q *Queries) MarkAuthTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuthTokenUsed, id)
	return err
}
