// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blog.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAdminBlogPosts = `-- name: CountAdminBlogPosts :one
SELECT COUNT(*)::bigint AS total
FROM blog_posts
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR status = $1
  )
  AND (
    $2::text IS NULL
    OR kind = $2
  )
  AND (
    $3::text IS NULL
    OR title ILIKE '%' || $3 || '%'
    OR slug ILIKE '%' || $3 || '%'
  )
`

type CountAdminBlogPostsParams struct {
	Status *string `json:"status"`
	Kind   *string `json:"kind"`
	Search *string `json:"search"`
}

func (q *Queries) CountAdminBlogPosts(ctx context.Context, arg CountAdminBlogPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminBlogPosts, arg.Status, arg.Kind, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPublishedBlogPosts = `-- name: CountPublishedBlogPosts :one
SELECT COUNT(*)::bigint AS total
FROM blog_posts
WHERE deleted_at IS NULL
  AND status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= NOW()
`

func (q *Queries) CountPublishedBlogPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedBlogPosts)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBlogPost = `-- name: CreateBlogPost :one
INSERT INTO blog_posts (
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW()
) RETURNING
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
`

type CreateBlogPostParams struct {
	ID           uuid.UUID  `json:"id"`
	Slug         string     `json:"slug"`
	Title        string     `json:"title"`
	Excerpt      string     `json:"excerpt"`
	Body         string     `json:"body"`
	Kind         string     `json:"kind"`
	CoverUrl     *string    `json:"cover_url"`
	CoverMediaID *uuid.UUID `json:"cover_media_id"`
	Status       string     `json:"status"`
	PublishedAt  *time.Time `json:"published_at"`
	Seo          []byte     `json:"seo"`
}

func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (BlogPost, error) {
	row := q.db.QueryRow(ctx, createBlogPost,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.Kind,
		arg.CoverUrl,
		arg.CoverMediaID,
		arg.Status,
		arg.PublishedAt,
		arg.Seo,
	)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.Kind,
		&i.CoverUrl,
		&i.CoverMediaID,
		&i.Status,
		&i.PublishedAt,
		&i.Seo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlogPostByID = `-- name: GetBlogPostByID :one
SELECT
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
FROM blog_posts
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetBlogPostByID(ctx context.Context, id uuid.UUID) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostByID, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.Kind,
		&i.CoverUrl,
		&i.CoverMediaID,
		&i.Status,
		&i.PublishedAt,
		&i.Seo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlogPostBySlug = `-- name: GetBlogPostBySlug :one
SELECT
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
FROM blog_posts
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostBySlug, slug)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.Kind,
		&i.CoverUrl,
		&i.CoverMediaID,
		&i.Status,
		&i.PublishedAt,
		&i.Seo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPublishedBlogPostBySlug = `-- name: GetPublishedBlogPostBySlug :one
SELECT
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
FROM blog_posts
WHERE slug = $1
  AND deleted_at IS NULL
  AND status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= NOW()
`

func (q *Queries) GetPublishedBlogPostBySlug(ctx context.Context, slug string) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getPublishedBlogPostBySlug, slug)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.Kind,
		&i.CoverUrl,
		&i.CoverMediaID,
		&i.Status,
		&i.PublishedAt,
		&i.Seo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdminBlogPosts = `-- name: ListAdminBlogPosts :many
SELECT
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
FROM blog_posts
WHERE deleted_at IS NULL
  AND (
    $3::text IS NULL
    OR status = $3
  )
  AND (
    $4::text IS NULL
    OR kind = $4
  )
  AND (
    $5::text IS NULL
    OR title ILIKE '%' || $5 || '%'
    OR slug ILIKE '%' || $5 || '%'
  )
ORDER BY COALESCE(published_at, created_at) DESC
LIMIT $1 OFFSET $2
`

type ListAdminBlogPostsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Kind   *string `json:"kind"`
	Search *string `json:"search"`
}

func (q *Queries) ListAdminBlogPosts(ctx context.Context, arg ListAdminBlogPostsParams) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listAdminBlogPosts,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Kind,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogPost{}
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Body,
			&i.Kind,
			&i.CoverUrl,
			&i.CoverMediaID,
			&i.Status,
			&i.PublishedAt,
			&i.Seo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogPosts = `-- name: ListPublishedBlogPosts :many
SELECT
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
FROM blog_posts
WHERE deleted_at IS NULL
  AND status = 'published'
  AND published_at IS NOT NULL
  AND published_at <= NOW()
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedBlogPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedBlogPosts(ctx context.Context, arg ListPublishedBlogPostsParams) ([]BlogPost, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlogPost{}
	for rows.Next() {
		var i BlogPost
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Body,
			&i.Kind,
			&i.CoverUrl,
			&i.CoverMediaID,
			&i.Status,
			&i.PublishedAt,
			&i.Seo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBlogPost = `-- name: SoftDeleteBlogPost :exec
UPDATE blog_posts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBlogPost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteBlogPost, id)
	return err
}

const updateBlogPost = `-- name: UpdateBlogPost :one
UPDATE blog_posts
SET slug = $2,
    title = $3,
    excerpt = $4,
    body = $5,
    kind = $6,
    cover_url = $7,
    cover_media_id = $8,
    status = $9,
    published_at = $10,
    seo = $11,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    slug,
    title,
    excerpt,
    body,
    kind,
    cover_url,
    cover_media_id,
    status,
    published_at,
    seo,
    created_at,
    updated_at,
    deleted_at
`

type UpdateBlogPostParams struct {
	ID           uuid.UUID  `json:"id"`
	Slug         string     `json:"slug"`
	Title        string     `json:"title"`
	Excerpt      string     `json:"excerpt"`
	Body         string     `json:"body"`
	Kind         string     `json:"kind"`
	CoverUrl     *string    `json:"cover_url"`
	CoverMediaID *uuid.UUID `json:"cover_media_id"`
	Status       string     `json:"status"`
	PublishedAt  *time.Time `json:"published_at"`
	Seo          []byte     `json:"seo"`
}

func (q *Queries) UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) (BlogPost, error) {
	row := q.db.QueryRow(ctx, updateBlogPost,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Excerpt,
		arg.Body,
		arg.Kind,
		arg.CoverUrl,
		arg.CoverMediaID,
		arg.Status,
		arg.PublishedAt,
		arg.Seo,
	)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Body,
		&i.Kind,
		&i.CoverUrl,
		&i.CoverMediaID,
		&i.Status,
		&i.PublishedAt,
		&i.Seo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
