// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cms.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createCMSVersion = `-- name: CreateCMSVersion :one
INSERT INTO cms_versions (
    id,
    page_id,
    version_number,
    summary,
    snapshot,
    published_by,
    published_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
) RETURNING
    id,
    page_id,
    version_number,
    summary,
    snapshot,
    published_by,
    published_at,
    created_at
`

type CreateCMSVersionParams struct {
	ID            uuid.UUID  `json:"id"`
	PageID        uuid.UUID  `json:"page_id"`
	VersionNumber int32      `json:"version_number"`
	Summary       string     `json:"summary"`
	Snapshot      []byte     `json:"snapshot"`
	PublishedBy   *uuid.UUID `json:"published_by"`
}

func (q *Queries) CreateCMSVersion(ctx context.Context, arg CreateCMSVersionParams) (CmsVersion, error) {
	row := q.db.QueryRow(ctx, createCMSVersion,
		arg.ID,
		arg.PageID,
		arg.VersionNumber,
		arg.Summary,
		arg.Snapshot,
		arg.PublishedBy,
	)
	var i CmsVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.Summary,
		&i.Snapshot,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCMSContentBySectionID = `-- name: GetCMSContentBySectionID :one
SELECT
    id,
    section_id,
    data,
    updated_by,
    created_at,
    updated_at
FROM cms_contents
WHERE section_id = $1
`

func (q *Queries) GetCMSContentBySectionID(ctx context.Context, sectionID uuid.UUID) (CmsContent, error) {
	row := q.db.QueryRow(ctx, getCMSContentBySectionID, sectionID)
	var i CmsContent
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Data,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCMSPageByID = `-- name: GetCMSPageByID :one
SELECT
    id,
    slug,
    title,
    status,
    seo,
    published_version_id,
    created_at,
    updated_at,
    deleted_at
FROM cms_pages
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCMSPageByID(ctx context.Context, id uuid.UUID) (CmsPage, error) {
	row := q.db.QueryRow(ctx, getCMSPageByID, id)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Seo,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCMSPageBySlug = `-- name: GetCMSPageBySlug :one
SELECT
    id,
    slug,
    title,
    status,
    seo,
    published_version_id,
    created_at,
    updated_at,
    deleted_at
FROM cms_pages
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCMSPageBySlug(ctx context.Context, slug string) (CmsPage, error) {
	row := q.db.QueryRow(ctx, getCMSPageBySlug, slug)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Seo,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCMSSectionByID = `-- name: GetCMSSectionByID :one
SELECT
    id,
    page_id,
    code,
    label,
    is_enabled,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM cms_sections
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCMSSectionByID(ctx context.Context, id uuid.UUID) (CmsSection, error) {
	row := q.db.QueryRow(ctx, getCMSSectionByID, id)
	var i CmsSection
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Code,
		&i.Label,
		&i.IsEnabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCMSVersionByID = `-- name: GetCMSVersionByID :one
SELECT
    id,
    page_id,
    version_number,
    summary,
    snapshot,
    published_by,
    published_at,
    created_at
FROM cms_versions
WHERE id = $1
`

func (q *Queries) GetCMSVersionByID(ctx context.Context, id uuid.UUID) (CmsVersion, error) {
	row := q.db.QueryRow(ctx, getCMSVersionByID, id)
	var i CmsVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.Summary,
		&i.Snapshot,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCMSVersionByPageAndNumber = `-- name: GetCMSVersionByPageAndNumber :one
SELECT
    id,
    page_id,
    version_number,
    summary,
    snapshot,
    published_by,
    published_at,
    created_at
FROM cms_versions
WHERE page_id = $1
  AND version_number = $2
`

type GetCMSVersionByPageAndNumberParams struct {
	PageID        uuid.UUID `json:"page_id"`
	VersionNumber int32     `json:"version_number"`
}

func (q *Queries) GetCMSVersionByPageAndNumber(ctx context.Context, arg GetCMSVersionByPageAndNumberParams) (CmsVersion, error) {
	row := q.db.QueryRow(ctx, getCMSVersionByPageAndNumber, arg.PageID, arg.VersionNumber)
	var i CmsVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.Summary,
		&i.Snapshot,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCMSVersionNumber = `-- name: GetLatestCMSVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int AS version_number
FROM cms_versions
WHERE page_id = $1
`

func (q *Queries) GetLatestCMSVersionNumber(ctx context.Context, pageID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestCMSVersionNumber, pageID)
	var version_number int32
	err := row.Scan(&version_number)
	return version_number, err
}

const listCMSContentsByPageID = `-- name: ListCMSContentsByPageID :many
SELECT
    c.id,
    c.section_id,
    c.data,
    c.updated_by,
    c.created_at,
    c.updated_at
FROM cms_contents c
INNER JOIN cms_sections s ON s.id = c.section_id
WHERE s.page_id = $1
  AND s.deleted_at IS NULL
ORDER BY s.sort_order, s.code
`

func (q *Queries) ListCMSContentsByPageID(ctx context.Context, pageID uuid.UUID) ([]CmsContent, error) {
	rows, err := q.db.Query(ctx, listCMSContentsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CmsContent{}
	for rows.Next() {
		var i CmsContent
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Data,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCMSPages = `-- name: ListCMSPages :many
SELECT
    id,
    slug,
    title,
    status,
    seo,
    published_version_id,
    created_at,
    updated_at,
    deleted_at
FROM cms_pages
WHERE deleted_at IS NULL
ORDER BY slug
`

func (q *Queries) ListCMSPages(ctx context.Context) ([]CmsPage, error) {
	rows, err := q.db.Query(ctx, listCMSPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CmsPage{}
	for rows.Next() {
		var i CmsPage
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Seo,
			&i.PublishedVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCMSSectionsByPageID = `-- name: ListCMSSectionsByPageID :many
SELECT
    id,
    page_id,
    code,
    label,
    is_enabled,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM cms_sections
WHERE page_id = $1
  AND deleted_at IS NULL
ORDER BY sort_order, code
`

func (q *Queries) ListCMSSectionsByPageID(ctx context.Context, pageID uuid.UUID) ([]CmsSection, error) {
	rows, err := q.db.Query(ctx, listCMSSectionsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CmsSection{}
	for rows.Next() {
		var i CmsSection
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Code,
			&i.Label,
			&i.IsEnabled,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCMSVersionsByPageID = `-- name: ListCMSVersionsByPageID :many
SELECT
    id,
    page_id,
    version_number,
    summary,
    snapshot,
    published_by,
    published_at,
    created_at
FROM cms_versions
WHERE page_id = $1
ORDER BY version_number DESC
`

func (q *Queries) ListCMSVersionsByPageID(ctx context.Context, pageID uuid.UUID) ([]CmsVersion, error) {
	rows, err := q.db.Query(ctx, listCMSVersionsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CmsVersion{}
	for rows.Next() {
		var i CmsVersion
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.VersionNumber,
			&i.Summary,
			&i.Snapshot,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCMSPagePublished = `-- name: MarkCMSPagePublished :one
UPDATE cms_pages
SET status = 'published',
    published_version_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    slug,
    title,
    status,
    seo,
    published_version_id,
    created_at,
    updated_at,
    deleted_at
`

type MarkCMSPagePublishedParams struct {
	ID                 uuid.UUID  `json:"id"`
	PublishedVersionID *uuid.UUID `json:"published_version_id"`
}

func (q *Queries) MarkCMSPagePublished(ctx context.Context, arg MarkCMSPagePublishedParams) (CmsPage, error) {
	row := q.db.QueryRow(ctx, markCMSPagePublished, arg.ID, arg.PublishedVersionID)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Seo,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCMSContentData = `-- name: UpdateCMSContentData :one
UPDATE cms_contents
SET data = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE section_id = $1
RETURNING
    id,
    section_id,
    data,
    updated_by,
    created_at,
    updated_at
`

type UpdateCMSContentDataParams struct {
	SectionID uuid.UUID  `json:"section_id"`
	Data      []byte     `json:"data"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateCMSContentData(ctx context.Context, arg UpdateCMSContentDataParams) (CmsContent, error) {
	row := q.db.QueryRow(ctx, updateCMSContentData, arg.SectionID, arg.Data, arg.UpdatedBy)
	var i CmsContent
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Data,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCMSPageSEO = `-- name: UpdateCMSPageSEO :one
UPDATE cms_pages
SET seo = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    slug,
    title,
    status,
    seo,
    published_version_id,
    created_at,
    updated_at,
    deleted_at
`

type UpdateCMSPageSEOParams struct {
	ID  uuid.UUID `json:"id"`
	Seo []byte    `json:"seo"`
}

func (q *Queries) UpdateCMSPageSEO(ctx context.Context, arg UpdateCMSPageSEOParams) (CmsPage, error) {
	row := q.db.QueryRow(ctx, updateCMSPageSEO, arg.ID, arg.Seo)
	var i CmsPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.Seo,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCMSSectionEnabled = `-- name: UpdateCMSSectionEnabled :one
UPDATE cms_sections
SET is_enabled = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    page_id,
    code,
    label,
    is_enabled,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

type UpdateCMSSectionEnabledParams struct {
	ID        uuid.UUID `json:"id"`
	IsEnabled bool      `json:"is_enabled"`
}

func (q *Queries) UpdateCMSSectionEnabled(ctx context.Context, arg UpdateCMSSectionEnabledParams) (CmsSection, error) {
	row := q.db.QueryRow(ctx, updateCMSSectionEnabled, arg.ID, arg.IsEnabled)
	var i CmsSection
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Code,
		&i.Label,
		&i.IsEnabled,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
