// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contact.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createContactMessage = `-- name: CreateContactMessage :one
INSERT INTO contact_messages (
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, 'new', $6, $7, NOW(), NOW()
) RETURNING
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
`

type CreateContactMessageParams struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Message   string    `json:"message"`
	IpAddress string    `json:"ip_address"`
	UserAgent string    `json:"user_agent"`
}

func (q *Queries) CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) (ContactMessage, error) {
	row := q.db.QueryRow(ctx, createContactMessage,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Message,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
