// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contact.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countContactMessagesAdmin = `-- name: CountContactMessagesAdmin :one
SELECT COUNT(*)::bigint AS total
FROM contact_messages
WHERE (
    $1::text IS NULL
    OR status = $1
)
AND (
    $2::text IS NULL
    OR email::text ILIKE '%' || $2 || '%'
    OR full_name ILIKE '%' || $2 || '%'
)
`

type CountContactMessagesAdminParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountContactMessagesAdmin(ctx context.Context, arg CountContactMessagesAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContactMessagesAdmin, arg.Status, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createContactMessage = `-- name: CreateContactMessage :one
INSERT INTO contact_messages (
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, 'new', $6, $7, NOW(), NOW()
) RETURNING
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
`

type CreateContactMessageParams struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Message   string    `json:"message"`
	IpAddress string    `json:"ip_address"`
	UserAgent string    `json:"user_agent"`
}

func (q *Queries) CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) (ContactMessage, error) {
	row := q.db.QueryRow(ctx, createContactMessage,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Message,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactMessageByID = `-- name: GetContactMessageByID :one
SELECT
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
FROM contact_messages
WHERE id = $1
`

func (q *Queries) GetContactMessageByID(ctx context.Context, id uuid.UUID) (ContactMessage, error) {
	row := q.db.QueryRow(ctx, getContactMessageByID, id)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactMessagesAdmin = `-- name: ListContactMessagesAdmin :many
SELECT
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
FROM contact_messages
WHERE (
    $3::text IS NULL
    OR status = $3
)
AND (
    $4::text IS NULL
    OR email::text ILIKE '%' || $4 || '%'
    OR full_name ILIKE '%' || $4 || '%'
)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListContactMessagesAdminParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) ListContactMessagesAdmin(ctx context.Context, arg ListContactMessagesAdminParams) ([]ContactMessage, error) {
	rows, err := q.db.Query(ctx, listContactMessagesAdmin,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactMessage{}
	for rows.Next() {
		var i ContactMessage
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Message,
			&i.Status,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactMessageStatus = `-- name: UpdateContactMessageStatus :one
UPDATE contact_messages
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    full_name,
    email,
    phone,
    message,
    status,
    ip_address,
    user_agent,
    created_at,
    updated_at
`

type UpdateContactMessageStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateContactMessageStatus(ctx context.Context, arg UpdateContactMessageStatusParams) (ContactMessage, error) {
	row := q.db.QueryRow(ctx, updateContactMessageStatus, arg.ID, arg.Status)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Message,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
