// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gallery.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countAdminGalleryItems = `-- name: CountAdminGalleryItems :one
SELECT COUNT(*)::bigint AS total
FROM gallery_items
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR location_slug = $1
  )
`

func (q *Queries) CountAdminGalleryItems(ctx context.Context, locationSlug *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminGalleryItems, locationSlug)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createGalleryItem = `-- name: CreateGalleryItem :one
INSERT INTO gallery_items (
    id,
    image_url,
    media_id,
    location_slug,
    category,
    alt_text,
    caption,
    sort_order,
    is_visible,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
) RETURNING
    id,
    image_url,
    media_id,
    location_slug,
    category,
    alt_text,
    caption,
    sort_order,
    is_visible,
    created_at,
    updated_at,
    deleted_at
`

type CreateGalleryItemParams struct {
	ID           uuid.UUID  `json:"id"`
	ImageUrl     string     `json:"image_url"`
	MediaID      *uuid.UUID `json:"media_id"`
	LocationSlug string     `json:"location_slug"`
	Category     string     `json:"category"`
	AltText      string     `json:"alt_text"`
	Caption      string     `json:"caption"`
	SortOrder    int32      `json:"sort_order"`
	IsVisible    bool       `json:"is_visible"`
}

func (q *Queries) CreateGalleryItem(ctx context.Context, arg CreateGalleryItemParams) (GalleryItem, error) {
	row := q.db.QueryRow(ctx, createGalleryItem,
		arg.ID,
		arg.ImageUrl,
		arg.MediaID,
		arg.LocationSlug,
		arg.Category,
		arg.AltText,
		arg.Caption,
		arg.SortOrder,
		arg.IsVisible,
	)
	var i GalleryItem
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.MediaID,
		&i.LocationSlug,
		&i.Category,
		&i.AltText,
		&i.Caption,
		&i.SortOrder,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGalleryItemByID = `-- name: GetGalleryItemByID :one
SELECT
    id,
    image_url,
    media_id,
    location_slug,
    category,
    alt_text,
    caption,
    sort_order,
    is_visible,
    created_at,
    updated_at,
    deleted_at
FROM gallery_items
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetGalleryItemByID(ctx context.Context, id uuid.UUID) (GalleryItem, error) {
	row := q.db.QueryRow(ctx, getGalleryItemByID, id)
	var i GalleryItem
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.MediaID,
		&i.LocationSlug,
		&i.Category,
		&i.AltText,
		&i.Caption,
		&i.SortOrder,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdminGalleryItems = `-- name: ListAdminGalleryItems :many
SELECT
    id,
    image_url,
    media_id,
    location_slug,
    category,
    alt_text,
    caption,
    sort_order,
    is_visible,
    created_at,
    updated_at,
    deleted_at
FROM gallery_items
WHERE deleted_at IS NULL
  AND (
    $3::text IS NULL
    OR location_slug = $3
  )
ORDER BY location_slug ASC, sort_order ASC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminGalleryItemsParams struct {
	Limit        int32   `json:"limit"`
	Offset       int32   `json:"offset"`
	LocationSlug *string `json:"location_slug"`
}

func (q *Queries) ListAdminGalleryItems(ctx context.Context, arg ListAdminGalleryItemsParams) ([]GalleryItem, error) {
	rows, err := q.db.Query(ctx, listAdminGalleryItems, arg.Limit, arg.Offset, arg.LocationSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GalleryItem{}
	for rows.Next() {
		var i GalleryItem
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.MediaID,
			&i.LocationSlug,
			&i.Category,
			&i.AltText,
			&i.Caption,
			&i.SortOrder,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicGalleryItems = `-- name: ListPublicGalleryItems :many
SELECT
    id,
    image_url,
    media_id,
    location_slug,
    category,
    alt_text,
    caption,
    sort_order,
    is_visible,
    created_at,
    updated_at,
    deleted_at
FROM gallery_items
WHERE deleted_at IS NULL
  AND is_visible = TRUE
  AND location_slug = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListPublicGalleryItems(ctx context.Context, locationSlug string) ([]GalleryItem, error) {
	rows, err := q.db.Query(ctx, listPublicGalleryItems, locationSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GalleryItem{}
	for rows.Next() {
		var i GalleryItem
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.MediaID,
			&i.LocationSlug,
			&i.Category,
			&i.AltText,
			&i.Caption,
			&i.SortOrder,
			&i.IsVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGalleryItem = `-- name: SoftDeleteGalleryItem :exec
UPDATE gallery_items
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGalleryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGalleryItem, id)
	return err
}

const updateGalleryItem = `-- name: UpdateGalleryItem :one
UPDATE gallery_items
SET image_url = $2,
    media_id = $3,
    location_slug = $4,
    category = $5,
    alt_text = $6,
    caption = $7,
    sort_order = $8,
    is_visible = $9,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    image_url,
    media_id,
    location_slug,
    category,
    alt_text,
    caption,
    sort_order,
    is_visible,
    created_at,
    updated_at,
    deleted_at
`

type UpdateGalleryItemParams struct {
	ID           uuid.UUID  `json:"id"`
	ImageUrl     string     `json:"image_url"`
	MediaID      *uuid.UUID `json:"media_id"`
	LocationSlug string     `json:"location_slug"`
	Category     string     `json:"category"`
	AltText      string     `json:"alt_text"`
	Caption      string     `json:"caption"`
	SortOrder    int32      `json:"sort_order"`
	IsVisible    bool       `json:"is_visible"`
}

func (q *Queries) UpdateGalleryItem(ctx context.Context, arg UpdateGalleryItemParams) (GalleryItem, error) {
	row := q.db.QueryRow(ctx, updateGalleryItem,
		arg.ID,
		arg.ImageUrl,
		arg.MediaID,
		arg.LocationSlug,
		arg.Category,
		arg.AltText,
		arg.Caption,
		arg.SortOrder,
		arg.IsVisible,
	)
	var i GalleryItem
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.MediaID,
		&i.LocationSlug,
		&i.Category,
		&i.AltText,
		&i.Caption,
		&i.SortOrder,
		&i.IsVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
