// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: loyalty.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLoyaltyAccountsAdmin = `-- name: CountLoyaltyAccountsAdmin :one
SELECT COUNT(*)::bigint AS count
FROM loyalty_accounts
WHERE deleted_at IS NULL
`

func (q *Queries) CountLoyaltyAccountsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLoyaltyAccountsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoyaltyTransactionsAdmin = `-- name: CountLoyaltyTransactionsAdmin :one
SELECT COUNT(*)::bigint AS count
FROM loyalty_transactions
WHERE ($1::uuid IS NULL OR user_id = $1)
`

func (q *Queries) CountLoyaltyTransactionsAdmin(ctx context.Context, userID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLoyaltyTransactionsAdmin, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLoyaltyTransactionsByUser = `-- name: CountLoyaltyTransactionsByUser :one
SELECT COUNT(*)::bigint AS count
FROM loyalty_transactions
WHERE user_id = $1
`

func (q *Queries) CountLoyaltyTransactionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLoyaltyTransactionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoyaltyAccount = `-- name: CreateLoyaltyAccount :one
INSERT INTO loyalty_accounts (
    id,
    user_id,
    balance,
    lifetime_earned,
    lifetime_redeemed,
    created_at,
    updated_at
) VALUES (
    $1, $2, 0, 0, 0, NOW(), NOW()
) RETURNING
    id,
    user_id,
    balance,
    lifetime_earned,
    lifetime_redeemed,
    created_at,
    updated_at,
    deleted_at
`

type CreateLoyaltyAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateLoyaltyAccount(ctx context.Context, arg CreateLoyaltyAccountParams) (LoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, createLoyaltyAccount, arg.ID, arg.UserID)
	var i LoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.LifetimeRedeemed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLoyaltyCampaign = `-- name: CreateLoyaltyCampaign :one
INSERT INTO loyalty_campaigns (
    id,
    code,
    name,
    description,
    starts_at,
    ends_at,
    point_multiplier,
    bonus_points,
    eligible_level_codes,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
) RETURNING
    id,
    code,
    name,
    description,
    starts_at,
    ends_at,
    point_multiplier,
    bonus_points,
    eligible_level_codes,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

type CreateLoyaltyCampaignParams struct {
	ID                 uuid.UUID `json:"id"`
	Code               string    `json:"code"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	StartsAt           time.Time `json:"starts_at"`
	EndsAt             time.Time `json:"ends_at"`
	PointMultiplier    string    `json:"point_multiplier"`
	BonusPoints        int32     `json:"bonus_points"`
	EligibleLevelCodes []byte    `json:"eligible_level_codes"`
	IsActive           bool      `json:"is_active"`
}

func (q *Queries) CreateLoyaltyCampaign(ctx context.Context, arg CreateLoyaltyCampaignParams) (LoyaltyCampaign, error) {
	row := q.db.QueryRow(ctx, createLoyaltyCampaign,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.PointMultiplier,
		arg.BonusPoints,
		arg.EligibleLevelCodes,
		arg.IsActive,
	)
	var i LoyaltyCampaign
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.PointMultiplier,
		&i.BonusPoints,
		&i.EligibleLevelCodes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLoyaltyRedemption = `-- name: CreateLoyaltyRedemption :one
INSERT INTO loyalty_redemptions (
    id,
    user_id,
    account_id,
    reward_id,
    transaction_id,
    points_spent,
    status,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
) RETURNING
    id,
    user_id,
    account_id,
    reward_id,
    transaction_id,
    points_spent,
    status,
    created_at
`

type CreateLoyaltyRedemptionParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	AccountID     uuid.UUID `json:"account_id"`
	RewardID      uuid.UUID `json:"reward_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	PointsSpent   int32     `json:"points_spent"`
	Status        string    `json:"status"`
}

func (q *Queries) CreateLoyaltyRedemption(ctx context.Context, arg CreateLoyaltyRedemptionParams) (LoyaltyRedemption, error) {
	row := q.db.QueryRow(ctx, createLoyaltyRedemption,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.RewardID,
		arg.TransactionID,
		arg.PointsSpent,
		arg.Status,
	)
	var i LoyaltyRedemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.RewardID,
		&i.TransactionID,
		&i.PointsSpent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createLoyaltyTransaction = `-- name: CreateLoyaltyTransaction :one
INSERT INTO loyalty_transactions (
    id,
    account_id,
    user_id,
    type,
    points,
    balance_after,
    source,
    description,
    related_entity_type,
    related_entity_id,
    campaign_id,
    actor_user_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW()
) RETURNING
    id,
    account_id,
    user_id,
    type,
    points,
    balance_after,
    source,
    description,
    related_entity_type,
    related_entity_id,
    campaign_id,
    actor_user_id,
    created_at
`

type CreateLoyaltyTransactionParams struct {
	ID                uuid.UUID  `json:"id"`
	AccountID         uuid.UUID  `json:"account_id"`
	UserID            uuid.UUID  `json:"user_id"`
	Type              string     `json:"type"`
	Points            int32      `json:"points"`
	BalanceAfter      int32      `json:"balance_after"`
	Source            string     `json:"source"`
	Description       string     `json:"description"`
	RelatedEntityType *string    `json:"related_entity_type"`
	RelatedEntityID   *uuid.UUID `json:"related_entity_id"`
	CampaignID        *uuid.UUID `json:"campaign_id"`
	ActorUserID       *uuid.UUID `json:"actor_user_id"`
}

func (q *Queries) CreateLoyaltyTransaction(ctx context.Context, arg CreateLoyaltyTransactionParams) (LoyaltyTransaction, error) {
	row := q.db.QueryRow(ctx, createLoyaltyTransaction,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Type,
		arg.Points,
		arg.BalanceAfter,
		arg.Source,
		arg.Description,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.CampaignID,
		arg.ActorUserID,
	)
	var i LoyaltyTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Type,
		&i.Points,
		&i.BalanceAfter,
		&i.Source,
		&i.Description,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.CampaignID,
		&i.ActorUserID,
		&i.CreatedAt,
	)
	return i, err
}

const decrementLoyaltyRewardStock = `-- name: DecrementLoyaltyRewardStock :one
UPDATE loyalty_rewards
SET stock = stock - 1,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
  AND stock IS NOT NULL
  AND stock > 0
RETURNING
    id,
    code,
    title,
    description,
    points_cost,
    stock,
    is_active,
    sort_order,
    data,
    created_at,
    updated_at,
    deleted_at
`

func (q *Queries) DecrementLoyaltyRewardStock(ctx context.Context, id uuid.UUID) (LoyaltyReward, error) {
	row := q.db.QueryRow(ctx, decrementLoyaltyRewardStock, id)
	var i LoyaltyReward
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.PointsCost,
		&i.Stock,
		&i.IsActive,
		&i.SortOrder,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoyaltyAccountByUserID = `-- name: GetLoyaltyAccountByUserID :one
SELECT
    id,
    user_id,
    balance,
    lifetime_earned,
    lifetime_redeemed,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_accounts
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetLoyaltyAccountByUserID(ctx context.Context, userID uuid.UUID) (LoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, getLoyaltyAccountByUserID, userID)
	var i LoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.LifetimeRedeemed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoyaltyAccountForUpdate = `-- name: GetLoyaltyAccountForUpdate :one
SELECT
    id,
    user_id,
    balance,
    lifetime_earned,
    lifetime_redeemed,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_accounts
WHERE user_id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetLoyaltyAccountForUpdate(ctx context.Context, userID uuid.UUID) (LoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, getLoyaltyAccountForUpdate, userID)
	var i LoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.LifetimeRedeemed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoyaltyCampaignByID = `-- name: GetLoyaltyCampaignByID :one
SELECT
    id,
    code,
    name,
    description,
    starts_at,
    ends_at,
    point_multiplier,
    bonus_points,
    eligible_level_codes,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_campaigns
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetLoyaltyCampaignByID(ctx context.Context, id uuid.UUID) (LoyaltyCampaign, error) {
	row := q.db.QueryRow(ctx, getLoyaltyCampaignByID, id)
	var i LoyaltyCampaign
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.PointMultiplier,
		&i.BonusPoints,
		&i.EligibleLevelCodes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoyaltyRewardByID = `-- name: GetLoyaltyRewardByID :one
SELECT
    id,
    code,
    title,
    description,
    points_cost,
    stock,
    is_active,
    sort_order,
    data,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_rewards
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetLoyaltyRewardByID(ctx context.Context, id uuid.UUID) (LoyaltyReward, error) {
	row := q.db.QueryRow(ctx, getLoyaltyRewardByID, id)
	var i LoyaltyReward
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.PointsCost,
		&i.Stock,
		&i.IsActive,
		&i.SortOrder,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoyaltyRewardForUpdate = `-- name: GetLoyaltyRewardForUpdate :one
SELECT
    id,
    code,
    title,
    description,
    points_cost,
    stock,
    is_active,
    sort_order,
    data,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_rewards
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetLoyaltyRewardForUpdate(ctx context.Context, id uuid.UUID) (LoyaltyReward, error) {
	row := q.db.QueryRow(ctx, getLoyaltyRewardForUpdate, id)
	var i LoyaltyReward
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.PointsCost,
		&i.Stock,
		&i.IsActive,
		&i.SortOrder,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLoyaltySettings = `-- name: GetLoyaltySettings :one
SELECT
    id,
    points_per_completed_reservation,
    expiration_strategy,
    expiration_months,
    created_at,
    updated_at
FROM loyalty_settings
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetLoyaltySettings(ctx context.Context) (LoyaltySetting, error) {
	row := q.db.QueryRow(ctx, getLoyaltySettings)
	var i LoyaltySetting
	err := row.Scan(
		&i.ID,
		&i.PointsPerCompletedReservation,
		&i.ExpirationStrategy,
		&i.ExpirationMonths,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveLoyaltyCampaigns = `-- name: ListActiveLoyaltyCampaigns :many
SELECT
    id,
    code,
    name,
    description,
    starts_at,
    ends_at,
    point_multiplier,
    bonus_points,
    eligible_level_codes,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_campaigns
WHERE deleted_at IS NULL
  AND is_active = TRUE
  AND starts_at <= NOW()
  AND ends_at >= NOW()
ORDER BY starts_at ASC
`

func (q *Queries) ListActiveLoyaltyCampaigns(ctx context.Context) ([]LoyaltyCampaign, error) {
	rows, err := q.db.Query(ctx, listActiveLoyaltyCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoyaltyCampaign{}
	for rows.Next() {
		var i LoyaltyCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.PointMultiplier,
			&i.BonusPoints,
			&i.EligibleLevelCodes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLoyaltyRewards = `-- name: ListActiveLoyaltyRewards :many
SELECT
    id,
    code,
    title,
    description,
    points_cost,
    stock,
    is_active,
    sort_order,
    data,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_rewards
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListActiveLoyaltyRewards(ctx context.Context) ([]LoyaltyReward, error) {
	rows, err := q.db.Query(ctx, listActiveLoyaltyRewards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoyaltyReward{}
	for rows.Next() {
		var i LoyaltyReward
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.PointsCost,
			&i.Stock,
			&i.IsActive,
			&i.SortOrder,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyAccountsAdmin = `-- name: ListLoyaltyAccountsAdmin :many
SELECT
    a.id,
    a.user_id,
    a.balance,
    a.lifetime_earned,
    a.lifetime_redeemed,
    a.created_at,
    a.updated_at,
    a.deleted_at,
    u.email AS user_email,
    u.full_name AS user_full_name
FROM loyalty_accounts a
INNER JOIN users u ON u.id = a.user_id
WHERE a.deleted_at IS NULL
ORDER BY a.updated_at DESC
LIMIT $1 OFFSET $2
`

type ListLoyaltyAccountsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListLoyaltyAccountsAdminRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	Balance          int32      `json:"balance"`
	LifetimeEarned   int32      `json:"lifetime_earned"`
	LifetimeRedeemed int32      `json:"lifetime_redeemed"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	UserEmail        string     `json:"user_email"`
	UserFullName     string     `json:"user_full_name"`
}

func (q *Queries) ListLoyaltyAccountsAdmin(ctx context.Context, arg ListLoyaltyAccountsAdminParams) ([]ListLoyaltyAccountsAdminRow, error) {
	rows, err := q.db.Query(ctx, listLoyaltyAccountsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoyaltyAccountsAdminRow{}
	for rows.Next() {
		var i ListLoyaltyAccountsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.LifetimeEarned,
			&i.LifetimeRedeemed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserEmail,
			&i.UserFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyCampaignsAdmin = `-- name: ListLoyaltyCampaignsAdmin :many
SELECT
    id,
    code,
    name,
    description,
    starts_at,
    ends_at,
    point_multiplier,
    bonus_points,
    eligible_level_codes,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_campaigns
WHERE deleted_at IS NULL
ORDER BY starts_at DESC
`

func (q *Queries) ListLoyaltyCampaignsAdmin(ctx context.Context) ([]LoyaltyCampaign, error) {
	rows, err := q.db.Query(ctx, listLoyaltyCampaignsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoyaltyCampaign{}
	for rows.Next() {
		var i LoyaltyCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.PointMultiplier,
			&i.BonusPoints,
			&i.EligibleLevelCodes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyRewardsAdmin = `-- name: ListLoyaltyRewardsAdmin :many
SELECT
    id,
    code,
    title,
    description,
    points_cost,
    stock,
    is_active,
    sort_order,
    data,
    created_at,
    updated_at,
    deleted_at
FROM loyalty_rewards
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListLoyaltyRewardsAdmin(ctx context.Context) ([]LoyaltyReward, error) {
	rows, err := q.db.Query(ctx, listLoyaltyRewardsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoyaltyReward{}
	for rows.Next() {
		var i LoyaltyReward
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.PointsCost,
			&i.Stock,
			&i.IsActive,
			&i.SortOrder,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyTransactionsAdmin = `-- name: ListLoyaltyTransactionsAdmin :many
SELECT
    t.id,
    t.account_id,
    t.user_id,
    t.type,
    t.points,
    t.balance_after,
    t.source,
    t.description,
    t.related_entity_type,
    t.related_entity_id,
    t.campaign_id,
    t.actor_user_id,
    t.created_at,
    u.email AS user_email,
    u.full_name AS user_full_name
FROM loyalty_transactions t
INNER JOIN users u ON u.id = t.user_id
WHERE ($3::uuid IS NULL OR t.user_id = $3)
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListLoyaltyTransactionsAdminParams struct {
	Limit  int32      `json:"limit"`
	Offset int32      `json:"offset"`
	UserID *uuid.UUID `json:"user_id"`
}

type ListLoyaltyTransactionsAdminRow struct {
	ID                uuid.UUID  `json:"id"`
	AccountID         uuid.UUID  `json:"account_id"`
	UserID            uuid.UUID  `json:"user_id"`
	Type              string     `json:"type"`
	Points            int32      `json:"points"`
	BalanceAfter      int32      `json:"balance_after"`
	Source            string     `json:"source"`
	Description       string     `json:"description"`
	RelatedEntityType *string    `json:"related_entity_type"`
	RelatedEntityID   *uuid.UUID `json:"related_entity_id"`
	CampaignID        *uuid.UUID `json:"campaign_id"`
	ActorUserID       *uuid.UUID `json:"actor_user_id"`
	CreatedAt         time.Time  `json:"created_at"`
	UserEmail         string     `json:"user_email"`
	UserFullName      string     `json:"user_full_name"`
}

func (q *Queries) ListLoyaltyTransactionsAdmin(ctx context.Context, arg ListLoyaltyTransactionsAdminParams) ([]ListLoyaltyTransactionsAdminRow, error) {
	rows, err := q.db.Query(ctx, listLoyaltyTransactionsAdmin, arg.Limit, arg.Offset, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoyaltyTransactionsAdminRow{}
	for rows.Next() {
		var i ListLoyaltyTransactionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.Type,
			&i.Points,
			&i.BalanceAfter,
			&i.Source,
			&i.Description,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.CampaignID,
			&i.ActorUserID,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoyaltyTransactionsByUser = `-- name: ListLoyaltyTransactionsByUser :many
SELECT
    id,
    account_id,
    user_id,
    type,
    points,
    balance_after,
    source,
    description,
    related_entity_type,
    related_entity_id,
    campaign_id,
    actor_user_id,
    created_at
FROM loyalty_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLoyaltyTransactionsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListLoyaltyTransactionsByUser(ctx context.Context, arg ListLoyaltyTransactionsByUserParams) ([]LoyaltyTransaction, error) {
	rows, err := q.db.Query(ctx, listLoyaltyTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoyaltyTransaction{}
	for rows.Next() {
		var i LoyaltyTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.Type,
			&i.Points,
			&i.BalanceAfter,
			&i.Source,
			&i.Description,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.CampaignID,
			&i.ActorUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoyaltyAccountBalances = `-- name: UpdateLoyaltyAccountBalances :one
UPDATE loyalty_accounts
SET balance = $2,
    lifetime_earned = $3,
    lifetime_redeemed = $4,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    user_id,
    balance,
    lifetime_earned,
    lifetime_redeemed,
    created_at,
    updated_at,
    deleted_at
`

type UpdateLoyaltyAccountBalancesParams struct {
	ID               uuid.UUID `json:"id"`
	Balance          int32     `json:"balance"`
	LifetimeEarned   int32     `json:"lifetime_earned"`
	LifetimeRedeemed int32     `json:"lifetime_redeemed"`
}

func (q *Queries) UpdateLoyaltyAccountBalances(ctx context.Context, arg UpdateLoyaltyAccountBalancesParams) (LoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, updateLoyaltyAccountBalances,
		arg.ID,
		arg.Balance,
		arg.LifetimeEarned,
		arg.LifetimeRedeemed,
	)
	var i LoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.LifetimeRedeemed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLoyaltyCampaign = `-- name: UpdateLoyaltyCampaign :one
UPDATE loyalty_campaigns
SET name = $2,
    description = $3,
    starts_at = $4,
    ends_at = $5,
    point_multiplier = $6,
    bonus_points = $7,
    eligible_level_codes = $8,
    is_active = $9,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    name,
    description,
    starts_at,
    ends_at,
    point_multiplier,
    bonus_points,
    eligible_level_codes,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

type UpdateLoyaltyCampaignParams struct {
	ID                 uuid.UUID `json:"id"`
	Name               string    `json:"name"`
	Description        string    `json:"description"`
	StartsAt           time.Time `json:"starts_at"`
	EndsAt             time.Time `json:"ends_at"`
	PointMultiplier    string    `json:"point_multiplier"`
	BonusPoints        int32     `json:"bonus_points"`
	EligibleLevelCodes []byte    `json:"eligible_level_codes"`
	IsActive           bool      `json:"is_active"`
}

func (q *Queries) UpdateLoyaltyCampaign(ctx context.Context, arg UpdateLoyaltyCampaignParams) (LoyaltyCampaign, error) {
	row := q.db.QueryRow(ctx, updateLoyaltyCampaign,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.PointMultiplier,
		arg.BonusPoints,
		arg.EligibleLevelCodes,
		arg.IsActive,
	)
	var i LoyaltyCampaign
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.PointMultiplier,
		&i.BonusPoints,
		&i.EligibleLevelCodes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
