// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: media.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const countMediaAssets = `-- name: CountMediaAssets :one
SELECT COUNT(*)::bigint AS count
FROM media_assets
WHERE deleted_at IS NULL
`

func (q *Queries) CountMediaAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (
    id,
    folder_id,
    file_name,
    storage_key,
    mime_type,
    size_bytes,
    alt_text,
    uploaded_by,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
) RETURNING
    id,
    folder_id,
    file_name,
    storage_key,
    mime_type,
    size_bytes,
    alt_text,
    uploaded_by,
    created_at,
    updated_at,
    deleted_at
`

type CreateMediaAssetParams struct {
	ID         uuid.UUID  `json:"id"`
	FolderID   *uuid.UUID `json:"folder_id"`
	FileName   string     `json:"file_name"`
	StorageKey string     `json:"storage_key"`
	MimeType   string     `json:"mime_type"`
	SizeBytes  int64      `json:"size_bytes"`
	AltText    string     `json:"alt_text"`
	UploadedBy *uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.ID,
		arg.FolderID,
		arg.FileName,
		arg.StorageKey,
		arg.MimeType,
		arg.SizeBytes,
		arg.AltText,
		arg.UploadedBy,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.FileName,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaAssetByID = `-- name: GetMediaAssetByID :one
SELECT
    id,
    folder_id,
    file_name,
    storage_key,
    mime_type,
    size_bytes,
    alt_text,
    uploaded_by,
    created_at,
    updated_at,
    deleted_at
FROM media_assets
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMediaAssetByID(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetByID, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.FileName,
		&i.StorageKey,
		&i.MimeType,
		&i.SizeBytes,
		&i.AltText,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT
    id,
    folder_id,
    file_name,
    storage_key,
    mime_type,
    size_bytes,
    alt_text,
    uploaded_by,
    created_at,
    updated_at,
    deleted_at
FROM media_assets
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMediaAssetsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMediaAssets(ctx context.Context, arg ListMediaAssetsParams) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listMediaAssets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.FileName,
			&i.StorageKey,
			&i.MimeType,
			&i.SizeBytes,
			&i.AltText,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMediaAsset = `-- name: SoftDeleteMediaAsset :exec
UPDATE media_assets
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMediaAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMediaAsset, id)
	return err
}
