// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: membership.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedReservationsByUser = `-- name: CountCompletedReservationsByUser :one
SELECT COUNT(*)::bigint AS count
FROM reservations
WHERE deleted_at IS NULL
  AND customer_user_id = $1
  AND status = 'completed'
`

func (q *Queries) CountCompletedReservationsByUser(ctx context.Context, customerUserID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedReservationsByUser, customerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembershipsAdmin = `-- name: CountMembershipsAdmin :one
SELECT COUNT(*)::bigint AS count
FROM memberships
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1)
  AND ($2::uuid IS NULL OR level_id = $2)
`

type CountMembershipsAdminParams struct {
	Status  *string    `json:"status"`
	LevelID *uuid.UUID `json:"level_id"`
}

func (q *Queries) CountMembershipsAdmin(ctx context.Context, arg CountMembershipsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsAdmin, arg.Status, arg.LevelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
    id,
    user_id,
    membership_number,
    level_id,
    status,
    qr_token,
    joined_at,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
) RETURNING
    id,
    user_id,
    membership_number,
    level_id,
    status,
    qr_token,
    joined_at,
    expires_at,
    created_at,
    updated_at,
    deleted_at
`

type CreateMembershipParams struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	MembershipNumber string     `json:"membership_number"`
	LevelID          uuid.UUID  `json:"level_id"`
	Status           string     `json:"status"`
	QrToken          string     `json:"qr_token"`
	JoinedAt         time.Time  `json:"joined_at"`
	ExpiresAt        *time.Time `json:"expires_at"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.UserID,
		arg.MembershipNumber,
		arg.LevelID,
		arg.Status,
		arg.QrToken,
		arg.JoinedAt,
		arg.ExpiresAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipNumber,
		&i.LevelID,
		&i.Status,
		&i.QrToken,
		&i.JoinedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMembershipHistory = `-- name: CreateMembershipHistory :exec
INSERT INTO membership_histories (
    id,
    membership_id,
    from_level_id,
    to_level_id,
    from_status,
    to_status,
    reason,
    trigger_source,
    actor_user_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
`

type CreateMembershipHistoryParams struct {
	ID            uuid.UUID  `json:"id"`
	MembershipID  uuid.UUID  `json:"membership_id"`
	FromLevelID   *uuid.UUID `json:"from_level_id"`
	ToLevelID     uuid.UUID  `json:"to_level_id"`
	FromStatus    *string    `json:"from_status"`
	ToStatus      *string    `json:"to_status"`
	Reason        string     `json:"reason"`
	TriggerSource string     `json:"trigger_source"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
}

func (q *Queries) CreateMembershipHistory(ctx context.Context, arg CreateMembershipHistoryParams) error {
	_, err := q.db.Exec(ctx, createMembershipHistory,
		arg.ID,
		arg.MembershipID,
		arg.FromLevelID,
		arg.ToLevelID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.TriggerSource,
		arg.ActorUserID,
	)
	return err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT
    id,
    user_id,
    membership_number,
    level_id,
    status,
    qr_token,
    joined_at,
    expires_at,
    created_at,
    updated_at,
    deleted_at
FROM memberships
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMembershipByID(ctx context.Context, id uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, id)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipNumber,
		&i.LevelID,
		&i.Status,
		&i.QrToken,
		&i.JoinedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT
    id,
    user_id,
    membership_number,
    level_id,
    status,
    qr_token,
    joined_at,
    expires_at,
    created_at,
    updated_at,
    deleted_at
FROM memberships
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMembershipByUserID(ctx context.Context, userID uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, userID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipNumber,
		&i.LevelID,
		&i.Status,
		&i.QrToken,
		&i.JoinedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMembershipLevelByCode = `-- name: GetMembershipLevelByCode :one
SELECT
    id,
    code,
    name,
    description,
    rank,
    qualification_rules,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_levels
WHERE code = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMembershipLevelByCode(ctx context.Context, code string) (MembershipLevel, error) {
	row := q.db.QueryRow(ctx, getMembershipLevelByCode, code)
	var i MembershipLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.QualificationRules,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMembershipLevelByID = `-- name: GetMembershipLevelByID :one
SELECT
    id,
    code,
    name,
    description,
    rank,
    qualification_rules,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_levels
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMembershipLevelByID(ctx context.Context, id uuid.UUID) (MembershipLevel, error) {
	row := q.db.QueryRow(ctx, getMembershipLevelByID, id)
	var i MembershipLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.QualificationRules,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveMembershipBenefits = `-- name: ListActiveMembershipBenefits :many
SELECT
    id,
    level_id,
    code,
    title,
    description,
    data,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_benefits
WHERE deleted_at IS NULL
  AND is_active = TRUE
  AND (level_id IS NULL OR level_id = $1)
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListActiveMembershipBenefits(ctx context.Context, levelID *uuid.UUID) ([]MembershipBenefit, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipBenefits, levelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipBenefit{}
	for rows.Next() {
		var i MembershipBenefit
		if err := rows.Scan(
			&i.ID,
			&i.LevelID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Data,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMembershipLevels = `-- name: ListActiveMembershipLevels :many
SELECT
    id,
    code,
    name,
    description,
    rank,
    qualification_rules,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_levels
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY rank ASC
`

func (q *Queries) ListActiveMembershipLevels(ctx context.Context) ([]MembershipLevel, error) {
	rows, err := q.db.Query(ctx, listActiveMembershipLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipLevel{}
	for rows.Next() {
		var i MembershipLevel
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Rank,
			&i.QualificationRules,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveMembershipBenefits = `-- name: ListAllActiveMembershipBenefits :many
SELECT
    id,
    level_id,
    code,
    title,
    description,
    data,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_benefits
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListAllActiveMembershipBenefits(ctx context.Context) ([]MembershipBenefit, error) {
	rows, err := q.db.Query(ctx, listAllActiveMembershipBenefits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipBenefit{}
	for rows.Next() {
		var i MembershipBenefit
		if err := rows.Scan(
			&i.ID,
			&i.LevelID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Data,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipBenefitsAdmin = `-- name: ListMembershipBenefitsAdmin :many
SELECT
    id,
    level_id,
    code,
    title,
    description,
    data,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_benefits
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListMembershipBenefitsAdmin(ctx context.Context) ([]MembershipBenefit, error) {
	rows, err := q.db.Query(ctx, listMembershipBenefitsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipBenefit{}
	for rows.Next() {
		var i MembershipBenefit
		if err := rows.Scan(
			&i.ID,
			&i.LevelID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Data,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipHistories = `-- name: ListMembershipHistories :many
SELECT
    h.id,
    h.membership_id,
    h.from_level_id,
    h.to_level_id,
    h.from_status,
    h.to_status,
    h.reason,
    h.trigger_source,
    h.actor_user_id,
    h.created_at,
    fl.code AS from_level_code,
    fl.name AS from_level_name,
    tl.code AS to_level_code,
    tl.name AS to_level_name
FROM membership_histories h
LEFT JOIN membership_levels fl ON fl.id = h.from_level_id
INNER JOIN membership_levels tl ON tl.id = h.to_level_id
WHERE h.membership_id = $1
ORDER BY h.created_at DESC
`

type ListMembershipHistoriesRow struct {
	ID            uuid.UUID  `json:"id"`
	MembershipID  uuid.UUID  `json:"membership_id"`
	FromLevelID   *uuid.UUID `json:"from_level_id"`
	ToLevelID     uuid.UUID  `json:"to_level_id"`
	FromStatus    *string    `json:"from_status"`
	ToStatus      *string    `json:"to_status"`
	Reason        string     `json:"reason"`
	TriggerSource string     `json:"trigger_source"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
	CreatedAt     time.Time  `json:"created_at"`
	FromLevelCode *string    `json:"from_level_code"`
	FromLevelName *string    `json:"from_level_name"`
	ToLevelCode   string     `json:"to_level_code"`
	ToLevelName   string     `json:"to_level_name"`
}

func (q *Queries) ListMembershipHistories(ctx context.Context, membershipID uuid.UUID) ([]ListMembershipHistoriesRow, error) {
	rows, err := q.db.Query(ctx, listMembershipHistories, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipHistoriesRow{}
	for rows.Next() {
		var i ListMembershipHistoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MembershipID,
			&i.FromLevelID,
			&i.ToLevelID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.TriggerSource,
			&i.ActorUserID,
			&i.CreatedAt,
			&i.FromLevelCode,
			&i.FromLevelName,
			&i.ToLevelCode,
			&i.ToLevelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipLevelsAdmin = `-- name: ListMembershipLevelsAdmin :many
SELECT
    id,
    code,
    name,
    description,
    rank,
    qualification_rules,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM membership_levels
WHERE deleted_at IS NULL
ORDER BY rank ASC
`

func (q *Queries) ListMembershipLevelsAdmin(ctx context.Context) ([]MembershipLevel, error) {
	rows, err := q.db.Query(ctx, listMembershipLevelsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembershipLevel{}
	for rows.Next() {
		var i MembershipLevel
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Rank,
			&i.QualificationRules,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsAdmin = `-- name: ListMembershipsAdmin :many
SELECT
    m.id,
    m.user_id,
    m.membership_number,
    m.level_id,
    m.status,
    m.qr_token,
    m.joined_at,
    m.expires_at,
    m.created_at,
    m.updated_at,
    m.deleted_at,
    u.email AS user_email,
    u.full_name AS user_full_name,
    l.code AS level_code,
    l.name AS level_name,
    l.rank AS level_rank
FROM memberships m
INNER JOIN users u ON u.id = m.user_id
INNER JOIN membership_levels l ON l.id = m.level_id
WHERE m.deleted_at IS NULL
  AND ($3::text IS NULL OR m.status = $3)
  AND ($4::uuid IS NULL OR m.level_id = $4)
ORDER BY m.joined_at DESC
LIMIT $1 OFFSET $2
`

type ListMembershipsAdminParams struct {
	Limit   int32      `json:"limit"`
	Offset  int32      `json:"offset"`
	Status  *string    `json:"status"`
	LevelID *uuid.UUID `json:"level_id"`
}

type ListMembershipsAdminRow struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	MembershipNumber string     `json:"membership_number"`
	LevelID          uuid.UUID  `json:"level_id"`
	Status           string     `json:"status"`
	QrToken          string     `json:"qr_token"`
	JoinedAt         time.Time  `json:"joined_at"`
	ExpiresAt        *time.Time `json:"expires_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DeletedAt        *time.Time `json:"deleted_at"`
	UserEmail        string     `json:"user_email"`
	UserFullName     string     `json:"user_full_name"`
	LevelCode        string     `json:"level_code"`
	LevelName        string     `json:"level_name"`
	LevelRank        int32      `json:"level_rank"`
}

func (q *Queries) ListMembershipsAdmin(ctx context.Context, arg ListMembershipsAdminParams) ([]ListMembershipsAdminRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsAdmin,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.LevelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsAdminRow{}
	for rows.Next() {
		var i ListMembershipsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MembershipNumber,
			&i.LevelID,
			&i.Status,
			&i.QrToken,
			&i.JoinedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserEmail,
			&i.UserFullName,
			&i.LevelCode,
			&i.LevelName,
			&i.LevelRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipLevel = `-- name: UpdateMembershipLevel :one
UPDATE memberships
SET level_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    user_id,
    membership_number,
    level_id,
    status,
    qr_token,
    joined_at,
    expires_at,
    created_at,
    updated_at,
    deleted_at
`

type UpdateMembershipLevelParams struct {
	ID      uuid.UUID `json:"id"`
	LevelID uuid.UUID `json:"level_id"`
}

func (q *Queries) UpdateMembershipLevel(ctx context.Context, arg UpdateMembershipLevelParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipLevel, arg.ID, arg.LevelID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipNumber,
		&i.LevelID,
		&i.Status,
		&i.QrToken,
		&i.JoinedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMembershipLevelRules = `-- name: UpdateMembershipLevelRules :one
UPDATE membership_levels
SET qualification_rules = $2,
    description = COALESCE($3, description),
    is_active = COALESCE($4, is_active),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    name,
    description,
    rank,
    qualification_rules,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

type UpdateMembershipLevelRulesParams struct {
	ID                 uuid.UUID   `json:"id"`
	QualificationRules []byte      `json:"qualification_rules"`
	Description        *string     `json:"description"`
	IsActive           pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateMembershipLevelRules(ctx context.Context, arg UpdateMembershipLevelRulesParams) (MembershipLevel, error) {
	row := q.db.QueryRow(ctx, updateMembershipLevelRules,
		arg.ID,
		arg.QualificationRules,
		arg.Description,
		arg.IsActive,
	)
	var i MembershipLevel
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.QualificationRules,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE memberships
SET status = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    user_id,
    membership_number,
    level_id,
    status,
    qr_token,
    joined_at,
    expires_at,
    created_at,
    updated_at,
    deleted_at
`

type UpdateMembershipStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipStatus, arg.ID, arg.Status)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MembershipNumber,
		&i.LevelID,
		&i.Status,
		&i.QrToken,
		&i.JoinedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
