// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID           uuid.UUID  `json:"id"`
	ActorUserID  *uuid.UUID `json:"actor_user_id"`
	Action       string     `json:"action"`
	ResourceType string     `json:"resource_type"`
	ResourceID   *string    `json:"resource_id"`
	IpAddress    string     `json:"ip_address"`
	UserAgent    string     `json:"user_agent"`
	Metadata     []byte     `json:"metadata"`
	CreatedAt    time.Time  `json:"created_at"`
}

type AuthToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	Purpose   string     `json:"purpose"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type CafeTable struct {
	ID        uuid.UUID  `json:"id"`
	Code      string     `json:"code"`
	Name      string     `json:"name"`
	Capacity  int32      `json:"capacity"`
	IsActive  bool       `json:"is_active"`
	SortOrder int32      `json:"sort_order"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type CmsContent struct {
	ID        uuid.UUID  `json:"id"`
	SectionID uuid.UUID  `json:"section_id"`
	Data      []byte     `json:"data"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type CmsPage struct {
	ID                 uuid.UUID  `json:"id"`
	Slug               string     `json:"slug"`
	Title              string     `json:"title"`
	Status             string     `json:"status"`
	Seo                []byte     `json:"seo"`
	PublishedVersionID *uuid.UUID `json:"published_version_id"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	DeletedAt          *time.Time `json:"deleted_at"`
}

type CmsSection struct {
	ID        uuid.UUID  `json:"id"`
	PageID    uuid.UUID  `json:"page_id"`
	Code      string     `json:"code"`
	Label     string     `json:"label"`
	IsEnabled bool       `json:"is_enabled"`
	SortOrder int32      `json:"sort_order"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type CmsVersion struct {
	ID            uuid.UUID  `json:"id"`
	PageID        uuid.UUID  `json:"page_id"`
	VersionNumber int32      `json:"version_number"`
	Summary       string     `json:"summary"`
	Snapshot      []byte     `json:"snapshot"`
	PublishedBy   *uuid.UUID `json:"published_by"`
	PublishedAt   time.Time  `json:"published_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type MediaAsset struct {
	ID         uuid.UUID  `json:"id"`
	FolderID   *uuid.UUID `json:"folder_id"`
	FileName   string     `json:"file_name"`
	StorageKey string     `json:"storage_key"`
	MimeType   string     `json:"mime_type"`
	SizeBytes  int64      `json:"size_bytes"`
	AltText    string     `json:"alt_text"`
	UploadedBy *uuid.UUID `json:"uploaded_by"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}

type MediaFolder struct {
	ID        uuid.UUID  `json:"id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Reservation struct {
	ID                uuid.UUID  `json:"id"`
	ReservationNumber string     `json:"reservation_number"`
	CustomerUserID    *uuid.UUID `json:"customer_user_id"`
	GuestFullName     string     `json:"guest_full_name"`
	GuestEmail        string     `json:"guest_email"`
	GuestPhone        string     `json:"guest_phone"`
	ReservationDate   time.Time  `json:"reservation_date"`
	ReservationTime   time.Time  `json:"reservation_time"`
	GuestCount        int32      `json:"guest_count"`
	Status            string     `json:"status"`
	Notes             string     `json:"notes"`
	TableID           *uuid.UUID `json:"table_id"`
	CancelledAt       *time.Time `json:"cancelled_at"`
	CancelReason      string     `json:"cancel_reason"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	DeletedAt         *time.Time `json:"deleted_at"`
}

type ReservationHistory struct {
	ID            uuid.UUID  `json:"id"`
	ReservationID uuid.UUID  `json:"reservation_id"`
	FromStatus    *string    `json:"from_status"`
	ToStatus      string     `json:"to_status"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
	Note          string     `json:"note"`
	CreatedAt     time.Time  `json:"created_at"`
}

type ReservationSetting struct {
	ID                  uuid.UUID `json:"id"`
	MinGuests           int32     `json:"min_guests"`
	MaxGuests           int32     `json:"max_guests"`
	MinAdvanceMinutes   int32     `json:"min_advance_minutes"`
	MaxAdvanceDays      int32     `json:"max_advance_days"`
	SlotIntervalMinutes int32     `json:"slot_interval_minutes"`
	DurationMinutes     int32     `json:"duration_minutes"`
	BufferMinutes       int32     `json:"buffer_minutes"`
	CancelCutoffMinutes int32     `json:"cancel_cutoff_minutes"`
	Timezone            string    `json:"timezone"`
	WeeklyHours         []byte    `json:"weekly_hours"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Session struct {
	ID               uuid.UUID  `json:"id"`
	UserID           uuid.UUID  `json:"user_id"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	UserAgent        string     `json:"user_agent"`
	IpAddress        string     `json:"ip_address"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
	LastActivityAt   time.Time  `json:"last_activity_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	FullName        string     `json:"full_name"`
	Status          string     `json:"status"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type UserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}
