// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reservations.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignReservationTable = `-- name: AssignReservationTable :one
UPDATE reservations
SET table_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
`

type AssignReservationTableParams struct {
	ID      uuid.UUID  `json:"id"`
	TableID *uuid.UUID `json:"table_id"`
}

func (q *Queries) AssignReservationTable(ctx context.Context, arg AssignReservationTableParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, assignReservationTable, arg.ID, arg.TableID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNumber,
		&i.CustomerUserID,
		&i.GuestFullName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.GuestCount,
		&i.Status,
		&i.Notes,
		&i.TableID,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countDuplicateGuestReservation = `-- name: CountDuplicateGuestReservation :one
SELECT COUNT(*)::bigint AS count
FROM reservations
WHERE deleted_at IS NULL
  AND guest_email = $1
  AND reservation_date = $2
  AND reservation_time = $3
  AND status IN ('pending', 'confirmed', 'checked_in')
`

type CountDuplicateGuestReservationParams struct {
	GuestEmail      string    `json:"guest_email"`
	ReservationDate time.Time `json:"reservation_date"`
	ReservationTime time.Time `json:"reservation_time"`
}

func (q *Queries) CountDuplicateGuestReservation(ctx context.Context, arg CountDuplicateGuestReservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDuplicateGuestReservation, arg.GuestEmail, arg.ReservationDate, arg.ReservationTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReservationsAdmin = `-- name: CountReservationsAdmin :one
SELECT COUNT(*)::bigint AS count
FROM reservations
WHERE deleted_at IS NULL
  AND ($1::date IS NULL OR reservation_date = $1)
  AND ($2::text IS NULL OR status = $2)
`

type CountReservationsAdminParams struct {
	ReservationDate *time.Time `json:"reservation_date"`
	Status          *string    `json:"status"`
}

func (q *Queries) CountReservationsAdmin(ctx context.Context, arg CountReservationsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReservationsAdmin, arg.ReservationDate, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCafeTable = `-- name: CreateCafeTable :one
INSERT INTO cafe_tables (
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
) RETURNING
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

type CreateCafeTableParams struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Capacity  int32     `json:"capacity"`
	IsActive  bool      `json:"is_active"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateCafeTable(ctx context.Context, arg CreateCafeTableParams) (CafeTable, error) {
	row := q.db.QueryRow(ctx, createCafeTable,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Capacity,
		arg.IsActive,
		arg.SortOrder,
	)
	var i CafeTable
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Capacity,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW()
) RETURNING
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
`

type CreateReservationParams struct {
	ID                uuid.UUID  `json:"id"`
	ReservationNumber string     `json:"reservation_number"`
	CustomerUserID    *uuid.UUID `json:"customer_user_id"`
	GuestFullName     string     `json:"guest_full_name"`
	GuestEmail        string     `json:"guest_email"`
	GuestPhone        string     `json:"guest_phone"`
	ReservationDate   time.Time  `json:"reservation_date"`
	ReservationTime   time.Time  `json:"reservation_time"`
	GuestCount        int32      `json:"guest_count"`
	Status            string     `json:"status"`
	Notes             string     `json:"notes"`
	TableID           *uuid.UUID `json:"table_id"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ID,
		arg.ReservationNumber,
		arg.CustomerUserID,
		arg.GuestFullName,
		arg.GuestEmail,
		arg.GuestPhone,
		arg.ReservationDate,
		arg.ReservationTime,
		arg.GuestCount,
		arg.Status,
		arg.Notes,
		arg.TableID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNumber,
		&i.CustomerUserID,
		&i.GuestFullName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.GuestCount,
		&i.Status,
		&i.Notes,
		&i.TableID,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createReservationClosedDay = `-- name: CreateReservationClosedDay :one
INSERT INTO reservation_closed_days (
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
`

type CreateReservationClosedDayParams struct {
	ID         uuid.UUID `json:"id"`
	ClosedDate time.Time `json:"closed_date"`
	Label      string    `json:"label"`
	Note       string    `json:"note"`
}

func (q *Queries) CreateReservationClosedDay(ctx context.Context, arg CreateReservationClosedDayParams) (ReservationClosedDay, error) {
	row := q.db.QueryRow(ctx, createReservationClosedDay,
		arg.ID,
		arg.ClosedDate,
		arg.Label,
		arg.Note,
	)
	var i ReservationClosedDay
	err := row.Scan(
		&i.ID,
		&i.ClosedDate,
		&i.Label,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservationHistory = `-- name: CreateReservationHistory :exec
INSERT INTO reservation_histories (
    id,
    reservation_id,
    from_status,
    to_status,
    actor_user_id,
    note,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
`

type CreateReservationHistoryParams struct {
	ID            uuid.UUID  `json:"id"`
	ReservationID uuid.UUID  `json:"reservation_id"`
	FromStatus    *string    `json:"from_status"`
	ToStatus      string     `json:"to_status"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
	Note          string     `json:"note"`
}

func (q *Queries) CreateReservationHistory(ctx context.Context, arg CreateReservationHistoryParams) error {
	_, err := q.db.Exec(ctx, createReservationHistory,
		arg.ID,
		arg.ReservationID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorUserID,
		arg.Note,
	)
	return err
}

const deleteReservationClosedDay = `-- name: DeleteReservationClosedDay :one
DELETE FROM reservation_closed_days
WHERE id = $1
RETURNING
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
`

func (q *Queries) DeleteReservationClosedDay(ctx context.Context, id uuid.UUID) (ReservationClosedDay, error) {
	row := q.db.QueryRow(ctx, deleteReservationClosedDay, id)
	var i ReservationClosedDay
	err := row.Scan(
		&i.ID,
		&i.ClosedDate,
		&i.Label,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCafeTableByID = `-- name: GetActiveCafeTableByID :one
SELECT
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM cafe_tables
WHERE id = $1
  AND deleted_at IS NULL
  AND is_active = TRUE
`

func (q *Queries) GetActiveCafeTableByID(ctx context.Context, id uuid.UUID) (CafeTable, error) {
	row := q.db.QueryRow(ctx, getActiveCafeTableByID, id)
	var i CafeTable
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Capacity,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCafeTableByID = `-- name: GetCafeTableByID :one
SELECT
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM cafe_tables
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCafeTableByID(ctx context.Context, id uuid.UUID) (CafeTable, error) {
	row := q.db.QueryRow(ctx, getCafeTableByID, id)
	var i CafeTable
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Capacity,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
FROM reservations
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNumber,
		&i.CustomerUserID,
		&i.GuestFullName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.GuestCount,
		&i.Status,
		&i.Notes,
		&i.TableID,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationByNumber = `-- name: GetReservationByNumber :one
SELECT
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
FROM reservations
WHERE reservation_number = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetReservationByNumber(ctx context.Context, reservationNumber string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByNumber, reservationNumber)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNumber,
		&i.CustomerUserID,
		&i.GuestFullName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.GuestCount,
		&i.Status,
		&i.Notes,
		&i.TableID,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReservationClosedDayByDate = `-- name: GetReservationClosedDayByDate :one
SELECT
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
FROM reservation_closed_days
WHERE closed_date = $1
`

func (q *Queries) GetReservationClosedDayByDate(ctx context.Context, closedDate time.Time) (ReservationClosedDay, error) {
	row := q.db.QueryRow(ctx, getReservationClosedDayByDate, closedDate)
	var i ReservationClosedDay
	err := row.Scan(
		&i.ID,
		&i.ClosedDate,
		&i.Label,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationClosedDayByID = `-- name: GetReservationClosedDayByID :one
SELECT
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
FROM reservation_closed_days
WHERE id = $1
`

func (q *Queries) GetReservationClosedDayByID(ctx context.Context, id uuid.UUID) (ReservationClosedDay, error) {
	row := q.db.QueryRow(ctx, getReservationClosedDayByID, id)
	var i ReservationClosedDay
	err := row.Scan(
		&i.ID,
		&i.ClosedDate,
		&i.Label,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationSettings = `-- name: GetReservationSettings :one
SELECT
    id,
    min_guests,
    max_guests,
    min_advance_minutes,
    max_advance_days,
    slot_interval_minutes,
    duration_minutes,
    buffer_minutes,
    cancel_cutoff_minutes,
    timezone,
    weekly_hours,
    created_at,
    updated_at
FROM reservation_settings
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetReservationSettings(ctx context.Context) (ReservationSetting, error) {
	row := q.db.QueryRow(ctx, getReservationSettings)
	var i ReservationSetting
	err := row.Scan(
		&i.ID,
		&i.MinGuests,
		&i.MaxGuests,
		&i.MinAdvanceMinutes,
		&i.MaxAdvanceDays,
		&i.SlotIntervalMinutes,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.CancelCutoffMinutes,
		&i.Timezone,
		&i.WeeklyHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCafeTables = `-- name: ListActiveCafeTables :many
SELECT
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM cafe_tables
WHERE deleted_at IS NULL
  AND is_active = TRUE
ORDER BY sort_order, code
`

func (q *Queries) ListActiveCafeTables(ctx context.Context) ([]CafeTable, error) {
	rows, err := q.db.Query(ctx, listActiveCafeTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CafeTable{}
	for rows.Next() {
		var i CafeTable
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Capacity,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveReservationsForDate = `-- name: ListActiveReservationsForDate :many
SELECT
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
FROM reservations
WHERE deleted_at IS NULL
  AND reservation_date = $1
  AND status IN ('pending', 'confirmed', 'checked_in')
`

func (q *Queries) ListActiveReservationsForDate(ctx context.Context, reservationDate time.Time) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listActiveReservationsForDate, reservationDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNumber,
			&i.CustomerUserID,
			&i.GuestFullName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.ReservationDate,
			&i.ReservationTime,
			&i.GuestCount,
			&i.Status,
			&i.Notes,
			&i.TableID,
			&i.CancelledAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCafeTablesAdmin = `-- name: ListCafeTablesAdmin :many
SELECT
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
FROM cafe_tables
WHERE deleted_at IS NULL
ORDER BY sort_order, code
`

func (q *Queries) ListCafeTablesAdmin(ctx context.Context) ([]CafeTable, error) {
	rows, err := q.db.Query(ctx, listCafeTablesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CafeTable{}
	for rows.Next() {
		var i CafeTable
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Capacity,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationClosedDays = `-- name: ListReservationClosedDays :many
SELECT
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
FROM reservation_closed_days
ORDER BY closed_date ASC
`

func (q *Queries) ListReservationClosedDays(ctx context.Context) ([]ReservationClosedDay, error) {
	rows, err := q.db.Query(ctx, listReservationClosedDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReservationClosedDay{}
	for rows.Next() {
		var i ReservationClosedDay
		if err := rows.Scan(
			&i.ID,
			&i.ClosedDate,
			&i.Label,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsAdmin = `-- name: ListReservationsAdmin :many
SELECT
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
FROM reservations
WHERE deleted_at IS NULL
  AND ($1::date IS NULL OR reservation_date = $1)
  AND ($2::text IS NULL OR status = $2)
ORDER BY reservation_date DESC, reservation_time DESC
LIMIT $4 OFFSET $3
`

type ListReservationsAdminParams struct {
	ReservationDate *time.Time `json:"reservation_date"`
	Status          *string    `json:"status"`
	Offset          int32      `json:"offset"`
	Limit           int32      `json:"limit"`
}

func (q *Queries) ListReservationsAdmin(ctx context.Context, arg ListReservationsAdminParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsAdmin,
		arg.ReservationDate,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNumber,
			&i.CustomerUserID,
			&i.GuestFullName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.ReservationDate,
			&i.ReservationTime,
			&i.GuestCount,
			&i.Status,
			&i.Notes,
			&i.TableID,
			&i.CancelledAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByCustomer = `-- name: ListReservationsByCustomer :many
SELECT
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
FROM reservations
WHERE customer_user_id = $1
  AND deleted_at IS NULL
ORDER BY reservation_date DESC, reservation_time DESC
`

func (q *Queries) ListReservationsByCustomer(ctx context.Context, customerUserID *uuid.UUID) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByCustomer, customerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ReservationNumber,
			&i.CustomerUserID,
			&i.GuestFullName,
			&i.GuestEmail,
			&i.GuestPhone,
			&i.ReservationDate,
			&i.ReservationTime,
			&i.GuestCount,
			&i.Status,
			&i.Notes,
			&i.TableID,
			&i.CancelledAt,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCafeTable = `-- name: SoftDeleteCafeTable :one
UPDATE cafe_tables
SET deleted_at = NOW(),
    is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

func (q *Queries) SoftDeleteCafeTable(ctx context.Context, id uuid.UUID) (CafeTable, error) {
	row := q.db.QueryRow(ctx, softDeleteCafeTable, id)
	var i CafeTable
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Capacity,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const sumActiveTableCapacity = `-- name: SumActiveTableCapacity :one
SELECT COALESCE(SUM(capacity), 0)::bigint AS total_capacity
FROM cafe_tables
WHERE deleted_at IS NULL
  AND is_active = TRUE
`

func (q *Queries) SumActiveTableCapacity(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumActiveTableCapacity)
	var total_capacity int64
	err := row.Scan(&total_capacity)
	return total_capacity, err
}

const updateCafeTable = `-- name: UpdateCafeTable :one
UPDATE cafe_tables
SET name = $2,
    capacity = $3,
    is_active = $4,
    sort_order = $5,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    code,
    name,
    capacity,
    is_active,
    sort_order,
    created_at,
    updated_at,
    deleted_at
`

type UpdateCafeTableParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Capacity  int32     `json:"capacity"`
	IsActive  bool      `json:"is_active"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdateCafeTable(ctx context.Context, arg UpdateCafeTableParams) (CafeTable, error) {
	row := q.db.QueryRow(ctx, updateCafeTable,
		arg.ID,
		arg.Name,
		arg.Capacity,
		arg.IsActive,
		arg.SortOrder,
	)
	var i CafeTable
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Capacity,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateReservationClosedDay = `-- name: UpdateReservationClosedDay :one
UPDATE reservation_closed_days
SET closed_date = $2,
    label = $3,
    note = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    closed_date,
    label,
    note,
    created_at,
    updated_at
`

type UpdateReservationClosedDayParams struct {
	ID         uuid.UUID `json:"id"`
	ClosedDate time.Time `json:"closed_date"`
	Label      string    `json:"label"`
	Note       string    `json:"note"`
}

func (q *Queries) UpdateReservationClosedDay(ctx context.Context, arg UpdateReservationClosedDayParams) (ReservationClosedDay, error) {
	row := q.db.QueryRow(ctx, updateReservationClosedDay,
		arg.ID,
		arg.ClosedDate,
		arg.Label,
		arg.Note,
	)
	var i ReservationClosedDay
	err := row.Scan(
		&i.ID,
		&i.ClosedDate,
		&i.Label,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationSettings = `-- name: UpdateReservationSettings :one
UPDATE reservation_settings
SET min_guests = $2,
    max_guests = $3,
    min_advance_minutes = $4,
    max_advance_days = $5,
    slot_interval_minutes = $6,
    duration_minutes = $7,
    buffer_minutes = $8,
    cancel_cutoff_minutes = $9,
    timezone = $10,
    weekly_hours = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    min_guests,
    max_guests,
    min_advance_minutes,
    max_advance_days,
    slot_interval_minutes,
    duration_minutes,
    buffer_minutes,
    cancel_cutoff_minutes,
    timezone,
    weekly_hours,
    created_at,
    updated_at
`

type UpdateReservationSettingsParams struct {
	ID                  uuid.UUID `json:"id"`
	MinGuests           int32     `json:"min_guests"`
	MaxGuests           int32     `json:"max_guests"`
	MinAdvanceMinutes   int32     `json:"min_advance_minutes"`
	MaxAdvanceDays      int32     `json:"max_advance_days"`
	SlotIntervalMinutes int32     `json:"slot_interval_minutes"`
	DurationMinutes     int32     `json:"duration_minutes"`
	BufferMinutes       int32     `json:"buffer_minutes"`
	CancelCutoffMinutes int32     `json:"cancel_cutoff_minutes"`
	Timezone            string    `json:"timezone"`
	WeeklyHours         []byte    `json:"weekly_hours"`
}

func (q *Queries) UpdateReservationSettings(ctx context.Context, arg UpdateReservationSettingsParams) (ReservationSetting, error) {
	row := q.db.QueryRow(ctx, updateReservationSettings,
		arg.ID,
		arg.MinGuests,
		arg.MaxGuests,
		arg.MinAdvanceMinutes,
		arg.MaxAdvanceDays,
		arg.SlotIntervalMinutes,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.CancelCutoffMinutes,
		arg.Timezone,
		arg.WeeklyHours,
	)
	var i ReservationSetting
	err := row.Scan(
		&i.ID,
		&i.MinGuests,
		&i.MaxGuests,
		&i.MinAdvanceMinutes,
		&i.MaxAdvanceDays,
		&i.SlotIntervalMinutes,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.CancelCutoffMinutes,
		&i.Timezone,
		&i.WeeklyHours,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE reservations
SET status = $2,
    cancelled_at = $3,
    cancel_reason = $4,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    reservation_number,
    customer_user_id,
    guest_full_name,
    guest_email,
    guest_phone,
    reservation_date,
    reservation_time,
    guest_count,
    status,
    notes,
    table_id,
    cancelled_at,
    cancel_reason,
    created_at,
    updated_at,
    deleted_at
`

type UpdateReservationStatusParams struct {
	ID           uuid.UUID  `json:"id"`
	Status       string     `json:"status"`
	CancelledAt  *time.Time `json:"cancelled_at"`
	CancelReason string     `json:"cancel_reason"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus,
		arg.ID,
		arg.Status,
		arg.CancelledAt,
		arg.CancelReason,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.ReservationNumber,
		&i.CustomerUserID,
		&i.GuestFullName,
		&i.GuestEmail,
		&i.GuestPhone,
		&i.ReservationDate,
		&i.ReservationTime,
		&i.GuestCount,
		&i.Status,
		&i.Notes,
		&i.TableID,
		&i.CancelledAt,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
