// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const countCustomersAdmin = `-- name: CountCustomersAdmin :one
SELECT COUNT(*)::bigint AS total
FROM users u
WHERE u.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = u.id
      AND r.code = 'customer'
  )
  AND (
    $1::text IS NULL
    OR u.status = $1
  )
  AND (
    $2::text IS NULL
    OR u.email::text ILIKE '%' || $2 || '%'
    OR u.full_name ILIKE '%' || $2 || '%'
  )
`

type CountCustomersAdminParams struct {
	Status *string `json:"status"`
	Search *string `json:"search"`
}

func (q *Queries) CountCustomersAdmin(ctx context.Context, arg CountCustomersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersAdmin, arg.Status, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countStaffUsersAdmin = `-- name: CountStaffUsersAdmin :one
SELECT COUNT(*)::bigint AS total
FROM users u
WHERE u.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = u.id
      AND r.code IN ('admin', 'super_admin')
  )
  AND (
    $1::text IS NULL
    OR u.status = $1
  )
  AND (
    $2::text IS NULL
    OR EXISTS (
      SELECT 1
      FROM user_roles ur
      INNER JOIN roles r ON r.id = ur.role_id
      WHERE ur.user_id = u.id
        AND r.code = $2
    )
  )
  AND (
    $3::text IS NULL
    OR u.email::text ILIKE '%' || $3 || '%'
    OR u.full_name ILIKE '%' || $3 || '%'
  )
`

type CountStaffUsersAdminParams struct {
	Status   *string `json:"status"`
	RoleCode *string `json:"role_code"`
	Search   *string `json:"search"`
}

func (q *Queries) CountStaffUsersAdmin(ctx context.Context, arg CountStaffUsersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffUsersAdmin, arg.Status, arg.RoleCode, arg.Search)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    full_name,
    status,
    email_verified_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
) RETURNING
    id,
    email,
    password_hash,
    full_name,
    status,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

type CreateUserParams struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	FullName        string     `json:"full_name"`
	Status          string     `json:"status"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Status,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUserStaffRoles = `-- name: DeleteUserStaffRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND role_id IN (
    SELECT id FROM roles WHERE code IN ('admin', 'super_admin')
  )
`

func (q *Queries) DeleteUserStaffRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserStaffRoles, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    password_hash,
    full_name,
    status,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE email = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    password_hash,
    full_name,
    status,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCustomersAdmin = `-- name: ListCustomersAdmin :many
SELECT
    u.id,
    u.email,
    u.full_name,
    u.status,
    u.email_verified_at,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM users u
WHERE u.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = u.id
      AND r.code = 'customer'
  )
  AND (
    $3::text IS NULL
    OR u.status = $3
  )
  AND (
    $4::text IS NULL
    OR u.email::text ILIKE '%' || $4 || '%'
    OR u.full_name ILIKE '%' || $4 || '%'
  )
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersAdminParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Search *string `json:"search"`
}

type ListCustomersAdminRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	FullName        string     `json:"full_name"`
	Status          string     `json:"status"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) ListCustomersAdmin(ctx context.Context, arg ListCustomersAdminParams) ([]ListCustomersAdminRow, error) {
	rows, err := q.db.Query(ctx, listCustomersAdmin,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersAdminRow{}
	for rows.Next() {
		var i ListCustomersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffUsersAdmin = `-- name: ListStaffUsersAdmin :many
SELECT
    u.id,
    u.email,
    u.full_name,
    u.status,
    u.email_verified_at,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM users u
WHERE u.deleted_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = u.id
      AND r.code IN ('admin', 'super_admin')
  )
  AND (
    $3::text IS NULL
    OR u.status = $3
  )
  AND (
    $4::text IS NULL
    OR EXISTS (
      SELECT 1
      FROM user_roles ur
      INNER JOIN roles r ON r.id = ur.role_id
      WHERE ur.user_id = u.id
        AND r.code = $4
    )
  )
  AND (
    $5::text IS NULL
    OR u.email::text ILIKE '%' || $5 || '%'
    OR u.full_name ILIKE '%' || $5 || '%'
  )
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListStaffUsersAdminParams struct {
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
	Status   *string `json:"status"`
	RoleCode *string `json:"role_code"`
	Search   *string `json:"search"`
}

type ListStaffUsersAdminRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	FullName        string     `json:"full_name"`
	Status          string     `json:"status"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) ListStaffUsersAdmin(ctx context.Context, arg ListStaffUsersAdminParams) ([]ListStaffUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listStaffUsersAdmin,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.RoleCode,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffUsersAdminRow{}
	for rows.Next() {
		var i ListStaffUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionCodes = `-- name: ListUserPermissionCodes :many
SELECT DISTINCT p.code
FROM user_roles ur
INNER JOIN role_permissions rp ON rp.role_id = ur.role_id
INNER JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.code
`

func (q *Queries) ListUserPermissionCodes(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleCodes = `-- name: ListUserRoleCodes :many
SELECT r.code
FROM user_roles ur
INNER JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.code
`

func (q *Queries) ListUserRoleCodes(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoleCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET status = 'active',
    email_verified_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    email,
    password_hash,
    full_name,
    status,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    email,
    password_hash,
    full_name,
    status,
    email_verified_at,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userHasRoleCode = `-- name: UserHasRoleCode :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1
      AND r.code = $2
)::bool AS has_role
`

type UserHasRoleCodeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) UserHasRoleCode(ctx context.Context, arg UserHasRoleCodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasRoleCode, arg.UserID, arg.Code)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const userIsStaff = `-- name: UserIsStaff :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1
      AND r.code IN ('admin', 'super_admin')
)::bool AS is_staff
`

func (q *Queries) UserIsStaff(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userIsStaff, userID)
	var is_staff bool
	err := row.Scan(&is_staff)
	return is_staff, err
}
